code = "Повторите код"
vcode = "Введите код указанный на картинке"
send = "Отправить"

; ** bbcodes.tpl **
b_b = "Полужирный"
b_i = "Наклонный текст"
b_u = "Подчеркнутый текст"
b_s = "Зачеркнутый текст"
b_img = "Вставка картинки"
b_up = "Загрузка файлов и изображений на сервер"
b_emo = "Вставка смайликов"
b_emo_title = "Смайлы"
b_url = "Вставка ссылки"
b_email = "Вставка e-mail"
b_media = "Вставка видео"
b_hide = "Скрытый текст"
b_quote = "Вставка цитаты"
b_code = "Вставка кода"
b_acronym = "Вставить акроним"
b_left = "Выравнивание по левому краю"
b_center = "По центру"
b_right = "Выравнивание по правому краю"
b_justify = "Выравнивание по двум сторонам"
b_color = "Выбор цвета"
b_spoiler = "Вставка спойлера"
b_list = "Вставка списка"
b_ol = "Вставка нумерованного списка"
b_br = "Разделение краткого и полного содержания"
b_pl = "Вставить переход на следующую страницу"

; ** main.tpl **
main_loading = "Загрузка. Пожалуйста, подождите..."

; ** news.short.tpl | news.search.tpl | news.full.tpl **
news_fixed = "Зафиксированный"
news_no_image = "нет изображний.."
news_screenshots = "Скриншоты"
news_comments = "Комментарии"
news_relatednews = "Также рекомендуем"
news_rpluse = "Нравится"
news_rminus = "Не нравится"

; ** registration.tpl **
registration_rules = "Я ознакомился с <a href='#'>правилами</a> и принимаю их."
registration_check_rules = "Ознакомьтесь с правилами и условиями."
registration_msg_login_warning = "Введенный логин уже существует или содержит неразрешенные символы!"
registration_msg_login_success = "Введенный вами логин свободен и может быть использован при регистрации."
registration_msg_email_warning = "Введенный вами email уже используется на сайте или имеет неправильный формат!"
registration_msg_email_success = "Введенный вами email может быть использован при регистрации."
registration_msg_password_warning = "Введенный вами пароль не совпадает с введеным ранее!"
registration_msg_password_success = "Пароли совпадают."
registration_descr = "Регистрация на нашем сайте позволит Вам быть его полноценным участником. Вы сможете добавлять новости на сайт, оставлять свои комментарии, просматривать скрытый текст и многое другое<br>В случае возникновения проблем с регистрацией, обратитесь к <a href='#'>администратору</a> сайта."

; ** search.form.tpl **
search_title = "Поиск по сайту"
search_btn = "Найти"

; ** usermenu.tpl **
user_hello = "Здравствуйте!"
user_bookmarks = "Закладки"

; ** /includes/menu.tpl **
menu_link_home = "Главная"
menu_link_forum = "Форум"
menu_link_documentation = "Документация"
menu_link_feedback = "Обратная связь"

; ** /includes/sidebar.tpl **
menu_categories_title = "Категории"

; ** /plugin/bookmarks **
bookmarks_page = "Все закладки"

; ** /plugin/comments **
addcomment = "Добавить комментарий"
your_name = "Ваше имя"
your_email = "Ваш e-mail"
comments_btn = "Добавить"
quote = "Ответить"
edit = "Редактировать"
delete = "Удалить"
close = "Закрыть"
comheader = "Все комментарии посетителей к данной новости"
regonly = "Уважаемый посетитель, Вы зашли на сайт как незарегистрированный пользователь.<br />Мы рекомендуем Вам <a href='/register/'>зарегистрироваться</a> либо <a href='/login/'>войти</a> на сайт под своим именем."
commforbidden = "Комментирование данной новости запрещено."

; ** /plugin/lastcomments **
lastcomments_all = "Все комментарии"

; ** /plugin/pm **
pm_current_messages = "Ящик заполнен на"
pm_max_messages = "сообщений"

; ** /plugin/tags **
tags_all = "Показать все теги"

; ** /plugin/uprofile **
uprofile_user_statistics = "Статистика пользователя"

; ** /plugin/voting **
vote_title = "Опрос"
vote_button = "Голосовать"
vote_results = "Результаты"
vote_votes = "Проголосовало"
vote_option = "начала необходимо выбрать вариант!"
vote_more = "Другие опросы..."